// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.9.0
// source: pb/pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PB_Get_FullMethodName    = "/pb.PB/Get"
	PB_Set_FullMethodName    = "/pb.PB/Set"
	PB_Delete_FullMethodName = "/pb.PB/Delete"
)

// PBClient is the client API for PB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PBClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error)
}

type pBClient struct {
	cc grpc.ClientConnInterface
}

func NewPBClient(cc grpc.ClientConnInterface) PBClient {
	return &pBClient{cc}
}

func (c *pBClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, PB_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBClient) Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, PB_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForDelete)
	err := c.cc.Invoke(ctx, PB_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PBServer is the server API for PB service.
// All implementations must embed UnimplementedPBServer
// for forward compatibility.
type PBServer interface {
	Get(context.Context, *Request) (*ResponseForGet, error)
	Set(context.Context, *Request) (*ResponseForGet, error)
	Delete(context.Context, *Request) (*ResponseForDelete, error)
	mustEmbedUnimplementedPBServer()
}

// UnimplementedPBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPBServer struct{}

func (UnimplementedPBServer) Get(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPBServer) Set(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedPBServer) Delete(context.Context, *Request) (*ResponseForDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPBServer) mustEmbedUnimplementedPBServer() {}
func (UnimplementedPBServer) testEmbeddedByValue()            {}

// UnsafePBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PBServer will
// result in compilation errors.
type UnsafePBServer interface {
	mustEmbedUnimplementedPBServer()
}

func RegisterPBServer(s grpc.ServiceRegistrar, srv PBServer) {
	// If the following call panics, it indicates UnimplementedPBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PB_ServiceDesc, srv)
}

func _PB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PB_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PB_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PB_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServer).Set(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PB_ServiceDesc is the grpc.ServiceDesc for PB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PB",
	HandlerType: (*PBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PB_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _PB_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PB_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/pb.proto",
}
